KalyanaInfo/Models/Shope.cs
using System;
using System.Collections.Generic;

namespace KalyanaInfo.Models
{
    public partial class Shope
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Images { get; set; }
        public int ShopeType { get; set; }
        public string Address { get; set; }
        public int UserId { get; set; }

        public virtual ShopeTypes ShopeTypeNavigation { get; set; }
        public virtual Person User { get; set; }
    }
}

KalyanaInfo/Models/ShopeTypes.cs
using System;
using System.Collections.Generic;

namespace KalyanaInfo.Models
{
    public partial class ShopeTypes
    {
        public ShopeTypes()
        {
            Shope = new HashSet<Shope>();
        }

        public int Id { get; set; }
        public string ShopeName { get; set; }

        public virtual ICollection<Shope> Shope { get; set; }
    }
}

KalyanaInfo/Areas/ShopeArea/Controllers/ShopesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KalyanaInfo.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.Extensions.Hosting;
using System.IO;

namespace KalyanaInfo.Areas.ShopeArea.Controllers
{
    [Area("ShopeArea")]
    public class ShopesController : Controller
    {
        private readonly kalyanadiaryContext _context;
        private readonly IHostEnvironment _ENV;

        public ShopesController(kalyanadiaryContext context, IHostEnvironment env)
        {
            _context = context;
            _ENV = env;
        }

        // GET: ShopeArea/Shopes
        public async Task<IActionResult> Index()
        {
            var kalyanadiaryContext = _context.Shope.Include(s => s.ShopeTypeNavigation).Include(s => s.User);
            return View(await kalyanadiaryContext.ToListAsync());
        }

        // GET: ShopeArea/Shopes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shope = await _context.Shope
                .Include(s => s.ShopeTypeNavigation)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shope == null)
            {
                return NotFound();
            }

            return View(shope);
        }

        // GET: ShopeArea/Shopes/Create
        public IActionResult Create()
        {
            ViewData["ShopeType"] = new SelectList(_context.ShopeTypes, "Id", "ShopeName");
            ViewData["UserId"] = new SelectList(_context.Person, "Id", "About");
            return View();
        }

        // POST: ShopeArea/Shopes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ShortDescription,LongDescription,ShopeType,Address,UserId")] Shope shope, List<IFormFile> images)
        {
            string ImagesName = "";
            if (images.Count > 0)
            {

                foreach (var image in images)
                {
                    string DirPath = _ENV.ContentRootPath + "\\wwwroot\\Images\\ShopeImages\\";
                    string FileEx = Path.GetExtension(image.FileName);
                    string fn = Guid.NewGuid() + FileEx;
                    string FinalFileName = DirPath + fn;
                    ImagesName += fn + ",";


                    FileStream stream = new FileStream(FinalFileName, FileMode.Create);
                    await image.CopyToAsync(stream);
                }
            }
            else
            {
                ImagesName = "NoImages";

            }


            if (ModelState.IsValid)
            {
                if (!ImagesName.Contains("NoImages"))
                {
                    ImagesName = ImagesName.Remove(ImagesName.LastIndexOf(","));
                }
                shope.Images = ImagesName;
                _context.Add(shope);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShopeType"] = new SelectList(_context.ShopeTypes, "Id", "ShopeName", shope.ShopeType);
            ViewData["UserId"] = new SelectList(_context.Person, "Id", "About", shope.UserId);
            return View(shope);
        }

        // GET: ShopeArea/Shopes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shope = await _context.Shope.FindAsync(id);
            if (shope == null)
            {
                return NotFound();
            }
            ViewData["ShopeType"] = new SelectList(_context.ShopeTypes, "Id", "ShopeName", shope.ShopeType);
            ViewData["UserId"] = new SelectList(_context.Person, "Id", "About", shope.UserId);
            return View(shope);
        }

        // POST: ShopeArea/Shopes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ShortDescription,LongDescription,Images,ShopeType,Address,UserId")] Shope shope,List<IFormFile> images)
        {
            string ImagesName = "";
            if(images.Count>0)
            {
                foreach (var image in images)
                {
                    string DirPath = _ENV.ContentRootPath + "\\wwwroot\\Images\\ShopeImages\\";
                    string FileEx = Path.GetExtension(image.FileName);
                    string fn = Guid.NewGuid() + FileEx;
                    string FinalFileName = DirPath + fn;
                    ImagesName += fn + ",";


                    FileStream stream = new FileStream(FinalFileName, FileMode.Create);
                    await image.CopyToAsync(stream);
                }
                ImagesName = ImagesName.Remove(ImagesName.LastIndexOf(","));
                shope.Images = ImagesName;
            }



            if (id != shope.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shope);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopeExists(shope.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShopeType"] = new SelectList(_context.ShopeTypes, "Id", "ShopeName", shope.ShopeType);
            ViewData["UserId"] = new SelectList(_context.Person, "Id", "About", shope.UserId);
            return View(shope);
        }

        // GET: ShopeArea/Shopes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shope = await _context.Shope
                .Include(s => s.ShopeTypeNavigation)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shope == null)
            {
                return NotFound();
            }

            return View(shope);
        }

        // POST: ShopeArea/Shopes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shope = await _context.Shope.FindAsync(id);
            _context.Shope.Remove(shope);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopeExists(int id)
        {
            return _context.Shope.Any(e => e.Id == id);
        }
        public async Task<IActionResult> MyShopes(int id)
        {
            if (HttpContext.Session.GetInt32("id") == id)
            {

                return View(await _context.Shope.Where(posts => posts.UserId == id).Include(p => p.User).ToListAsync());
            }
            return View();

        }
        public string DeleteShope(int? id)
        {
            try
            {
                var shop = _context.Shope.Find(id);
                Shope p = shop;
                if (p != null)
                {
                    _context.Remove(p);
                    _context.SaveChanges();
                    return "1";
                }
            }
            catch (Exception e)
            {
                return e.Message;
            }
            return "0";
        }
        

    }
}

KalyanaInfo/Areas/ShopeArea/Views/Shopes/Create.cshtml
@model KalyanaInfo.Models.Shope

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Shope</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <p><input id="images" name="images" type="file" accept="image/*" style="display:none" multiple></p>
                <p><label for="images" style="cursor: pointer;">Upload Images</label></p>
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>
            <div class="row" id="a-0">
                
            </div>
            <div class="form-group" >
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <textarea asp-for="ShortDescription" class="form-control" style="height:110px" maxlength="200" ></textarea>
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <textarea asp-for="LongDescription" class="form-control" style="height:110px" maxlength="500" ></textarea>
                <span asp-validation-for="LongDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShopeType" class="control-label"></label>
                <select asp-for="ShopeType" class ="form-control" asp-items="ViewBag.ShopeType"></select>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" value="@Context.Session.GetInt32("id")" asp-for="UserId" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts
{
<script>
    
        $('input#images').change(function () {
            var files = $(this)[0].files;
            if (files.length > 10)
            {
                alert("you can select max 10 files.");
            }
            else
            {
                $("#a-0").html("");
                for (var i = 0; i < files.length; i++)
                {
                    $('<div class="col-md-4"><div class="thumbnail"><img src="' + URL.createObjectURL(event.target.files[i]) + '" alt="Lights" style="width:100%"></div></div>').appendTo("#a-0");
                }
            }
        });
</script>



}

KalyanaInfo/Areas/ShopeArea/Views/Shopes/Delete.cshtml
@model KalyanaInfo.Models.Shope

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shope</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LongDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Images)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Images)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShopeTypeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShopeTypeNavigation.ShopeName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.About)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KalyanaInfo/Areas/ShopeArea/Views/Shopes/Details.cshtml
@model KalyanaInfo.Models.Shope


@{
    ViewData["Title"] = "Details";
}@{
    var i = 0;
    var images = Model.Images.Split(",");
}
<h3>ShopeImages</h3>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        @foreach (var a in images)
        {
            <li data-target="#carouselExampleIndicators-@a" data-slide-to="@i"></li>
            i++;
        }

    </ol>
    <div class="carousel-inner">

        <div class="carousel-item active">
            <img class="d-block w-100" src="~/Images/ShopeImages/@images[0]" alt="First slide">
        </div>

        @foreach (var img in images)
        {
            <div class="carousel-item ">
                <img class="d-block w-100" src="~/Images/ShopeImages/@img" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Owner</h5>
                    <p>Mr. @Model.User.Name is the owner</p>

                </div>
            </div>
        }
    </div>

    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>



















<section id="person">
    <div>
        @if ((Context.Session.GetInt32("id") == Model.Id))
        {
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary">EditShopeDdetails</a>
        }
        @if ((Context.Session.GetInt32("id") == Model.Id))
        {
            <a class="btn btn-danger " data-toggle="modal" data-target="#exampleModal-@Model.Id">RemoveShope</a>
        }
        <a asp-action="Index" class="btn btn-primary">Home</a>
    </div>
    <div class="modal" id="exampleModal-@Model.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Really want to delete...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="delperson">ConfirmDelete</button>
                </div>
            </div>
        </div>
    </div>

    <div class="mr-auto ml-auto mt-3 ">
        <h3>@Html.DisplayFor(model => model.Name)</h3>
    </div>
    <hr />
    <div>
        <h4>@Html.DisplayFor(model => model.Name) Details:</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-12 thead-light border-bottom mt-3" style="color:royalblue" id="Pinfo"><span class="fa fa-chevron-circle-down"></span> Shope Info</dt>
            <dd></dd>
        </dl>
        <dl id="PInfo">
            <dt class="col-sm-2"> OwnerName</dt>
            <dd class="col-sm-10">@Html.DisplayFor(model => model.User.Name)</dd>
            <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.Name)</dt>
            <dd class="col-sm-10">@Html.DisplayFor(model => model.Name)</dd>
            <dt class="col-sm-2"> @Html.DisplayNameFor(model => model.Address)</dt>
            <dd class="col-sm-10">@Html.DisplayFor(model => model.Address)</dd>
        </dl>
        <dl>
            <dt class="col-sm-12 font-weight-bold border-bottom mt-3" style="color:royalblue" id="Cinfo"><span class="fa fa-chevron-circle-down"></span>Contact Info</dt>
            <dd></dd>
        </dl>
        <dl id="CInfo">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ShortDescription)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ShortDescription)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LongDescription)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LongDescription)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address)
            </dd>

        </dl>
        <input type="hidden" value="@Model.Id" id="shop" name="shop" />
    </div>
    <div id="disqus_thread"></div>


</section>
@section Scripts
{
    <script>

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

        var disqus_config = function () {
        this.page.url = @Context.Request.Host@Context.Request.Path;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = @Model.Id; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };

        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://kalyanainfo-azurewebsites-net.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

    <script>
        $('.carousel').carousel();
        $(function () {

            $("#PInfo").hide();
            $("#CInfo").hide();
         });
        $("#Pinfo").click(function () {
            $("#PInfo").toggle();
        });

        $("#Cinfo").click(function () {
            $("#CInfo").toggle();
        });
        $(function () {
            var depid = $("#shop").val();

            $.ajax({
                url: '/ShopeArea/Shopes/DeleteShope',
                type: 'POST',
                data: {
                    id: depid
                },
                success: function (returndata) {
                    if (returndata == "1") {
                        $("#PostDiv").hide();
                        $("#exampleModal-" + depid).modal('hide');
                    } else {
                        alert("Not Found");
                    }
                },
                Error: function (er) {
                    alert(er)
                }
            });
        });

        $(function () {

            $("#delperson").click(function () {

                $.ajax({
                url: '/PeopleArea/People/DeletePerson',
                type: 'POST',
                data: {
                    id:@Model.Id
                },
                success: function (returndata)
                {
                    if (returndata == "1")
                    {
                        $("#person").hide();
                        $("#exampleModal-@Model.Id").modal('hide');
                    }
                    else
                    {
                        alert(returndata);
                        alert("Not Found");
                    }
                },
                Error: function (er) {
                    alert(er)
                }



            })
           });

        });


    </script>



}

KalyanaInfo/Areas/ShopeArea/Views/Shopes/Edit.cshtml
@model KalyanaInfo.Models.Shope

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Shope</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Images" />
            <div class="form-group">
                <p><input id="images" name="images" type="file" accept="image/*" style="display:none" multiple></p>
                <p><label for="images" style="cursor: pointer;">Upload Images</label></p>
                <span asp-validation-for="Images" class="text-danger"></span>
            </div>
            <div class="row" id="a-0">

            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <input asp-for="LongDescription" class="form-control" />
                <span asp-validation-for="LongDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShopeType" class="control-label"></label>
                <select asp-for="ShopeType" class="form-control" asp-items="ViewBag.ShopeType"></select>
                <span asp-validation-for="ShopeType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" value="@Context.Session.GetInt32("id")" asp-for="UserId" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts
{
<script>

    $('input#images').change(function () {
        var files = $(this)[0].files;
        if (files.length > 10) {
            alert("you can select max 10 files.");
        }
        else {
            $("#a-0").html("");
            for (var i = 0; i < files.length; i++) {
                $('<div class="col-md-4"><div class="thumbnail"><img src="' + URL.createObjectURL(event.target.files[i]) + '" alt="Lights" style="width:100%"></div></div>').appendTo("#a-0");
            }
        }
    });


</script>




}

KalyanaInfo/Areas/ShopeArea/Views/Shopes/Index.cshtml
@model IEnumerable<KalyanaInfo.Models.Shope>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>  @if (Model != null)
{

    @foreach (var item in Model.Reverse())
    {

        <div class="col-md-5 m-2 d-inline-block">

            <div class="card border-primary  d-inline-block col-md-6 " style="max-width: 30rem;">
                <a asp-action="Details" asp-route-id="@item.Id">
                    <div class="card-header">
                        <span>
                            @{
                                var list=@item.Images.Split(",");
                            }
                            <img src="~/Images/ShopeImages/@list[0]" alt="No Image" class="img-thumbnail" style="border-radius:100%;border:1px solid gray;display:inline-block" width="100" height="100" />
                        </span>
                        <span>@Html.DisplayFor(modelItem => item.Name)</span>
                       
                    </div>
                    <div class="card-body">
                        <p>About: @Html.DisplayFor(modelItem => item.ShortDescription)</p>
                    </div>
                </a>
                <div>

                    <a asp-action="Details" class="btn btn-info" asp-route-id="@item.Id">Details</a>

                </div>
            </div>
        </div>



    }

}

KalyanaInfo/Areas/ShopeArea/Views/Shopes/MyShopes.cshtml
@model IList<Shope>


@foreach (var item in Model.Reverse())
{

    <div class="card mb-3">
        <div>
            <h6 class="card-header"><img src="~/Images/PersonImages/@item.User.Image" style="height:60px;width:60px;border-radius:50%;margin-right:4px" />@item.User.Name</h6>

        </div>
        <div class="card-body">
           
            <p class="card-text">@item.ShortDescription</p>
        </div>
        @if (!item.Images.Equals("NoImage"))
        {
            string[] list = item.Images.Split(",");

            <img style="height: 200px; width: 99%; display: block; margin-bottom:3px" src="~/Images/ShopeImages/@list[0]" alt="Card image">
        }
       
        <div class="card-body">
            @if (!string.IsNullOrEmpty(Context.Session.GetString("name")))
            {
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Edit</a>
                <a class="btn btn-danger " data-toggle="modal" data-target="#exampleModal-@item.Id">Delete</a>
            }

            <a asp-area="ShopeArea" asp-controller="Shopes" asp-action="Details" asp-route-id="@item.Id" class="btn btn-danger">Commint</a>
            <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample-@item.Id" aria-expanded="false" aria-controls="collapseExample-@item.Id">
                <span class="fa fa-share"></span>
            </a>
            <div class="collapse" id="collapseExample-@item.Id">
                <div class="card card-body">
                    <div class="sharethis-inline-share-buttons"></div>
                </div>
            </div>
        </div>

    </div>
    //Modal
    <div class="modal" id="exampleModal-@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Really want to delete...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger delpost" id="delbutton" data-cid="@item.Id">ConfirmDelete</button>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts
{
    <script>
        $(function () {
            $(".delpost").click(function () {

                var dep = $(this);

                var depid = dep.data('cid');

                $.ajax({
                    url: '/ShopeArea/Shopes/DeleteShope',
                    type: 'POST',
                    data: {
                        id: depid
                    },
                    success: function (returndata) {
                        if (returndata == "1") {
                            $("#PostDiv").hide();
                            $("#exampleModal-" + depid).modal('hide');
                        } else {
                            alert("Not Found");
                        }
                    },
                    Error: function (er) {
                        alert(er)
                    }
                })
            })
        });
    </script>

}