KalyanaInfo/Models/Person.cs
using System;
using System.Collections.Generic;

namespace KalyanaInfo.Models
{
    public partial class Person
    {
        public Person()
        {
            MessageMessageFromNavigation = new HashSet<Message>();
            MessageMessageToNavigation = new HashSet<Message>();
            Mosque = new HashSet<Mosque>();
            Post = new HashSet<Post>();
            School = new HashSet<School>();
            Shope = new HashSet<Shope>();
            Video = new HashSet<Video>();
           
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public string SonOrDaughterOf { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public string Hobby { get; set; }
        public string Mobile { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public DateTime DateOfBirth { get; set; }
        public int HasMobile { get; set; }
        public int Gender { get; set; }
        public int Education { get; set; }
        public int Profession { get; set; }
        public int Vehicle { get; set; }
        public int Family { get; set; }
        public string About { get; set; }
        public string Married { get; set; }
        public string RecoveryEmail { get; set; }
        public string Private { get; set; }

        public virtual Education EducationNavigation { get; set; }
        public virtual Family FamilyNavigation { get; set; }
        public virtual Gender GenderNavigation { get; set; }
        public virtual Mobile HasMobileNavigation { get; set; }
        public virtual Profession ProfessionNavigation { get; set; }
        public virtual Vehicle VehicleNavigation { get; set; }
        public virtual ICollection<Mosque> Mosque { get; set; }
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<School> School { get; set; }
        public virtual ICollection<Shope> Shope { get; set; }
        public virtual ICollection<Video> Video { get; set; }
      
        public HashSet<Message> MessageMessageFromNavigation { get; }
        public HashSet<Message> MessageMessageToNavigation { get; }
    }
}

KalyanaInfo/Areas/PeopleArea/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KalyanaInfo.Models;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using System.IO;
using System.Linq.Expressions;
using KalyanaInfo.Areas.Validators;
using System.Net.Mail;
using Microsoft.Data.SqlClient.Server;

namespace KalyanaInfo.Areas.PeopleArea.Controllers
{
    [Area("PeopleArea")]
    public class PeopleController : Controller
    {
        private readonly kalyanadiaryContext _context;
        private readonly IActionContextAccessor accessor;
        private readonly IHostEnvironment _ENV;
        public PeopleController(kalyanadiaryContext context,IActionContextAccessor ac, IHostEnvironment env)
        {
            _context = context;
            accessor = ac;
            _ENV = env;
        }

        // GET: PeopleArea/People
        public async Task<IActionResult> Index(string query,string By)
        {
           
            if (By!=null&&query!=null)
            {
                if(By.Contains("Name"))
                {
                   var kalyanadiaryContext = _context.Person.Include(p => p.EducationNavigation).Include(p => p.FamilyNavigation).Include(p => p.GenderNavigation).Include(p => p.HasMobileNavigation).Include(p => p.ProfessionNavigation).Include(p => p.VehicleNavigation).Where(p => p.Name.Contains(query));
                    return View(await kalyanadiaryContext.ToListAsync());

                }
                else if (By.Contains("Address"))
                {
                    var kalyanadiaryContext = _context.Person.Include(p => p.EducationNavigation).Include(p => p.FamilyNavigation).Include(p => p.GenderNavigation).Include(p => p.HasMobileNavigation).Include(p => p.ProfessionNavigation).Include(p => p.VehicleNavigation).Where(p => p.Address.Contains(query));
                    return View(await kalyanadiaryContext.ToListAsync());
                }
                 
                else if (By.Contains("Contact"))
                {
                    var kalyanadiaryContext = _context.Person.Include(p => p.EducationNavigation).Include(p => p.FamilyNavigation).Include(p => p.GenderNavigation).Include(p => p.HasMobileNavigation).Include(p => p.ProfessionNavigation).Include(p => p.VehicleNavigation).Where(p => p.Mobile.Contains(query));
                    return View(await kalyanadiaryContext.ToListAsync());
                }
                else if (By.Contains("Profession"))
                {
                    var kalyanadiaryContext = _context.Profession.Where(p=>p.Name.Contains(query));
                    return View(await kalyanadiaryContext.ToListAsync());
                }
             
            }            
            var kalyanadiaryContex = _context.Person.Include(p => p.EducationNavigation).Include(p => p.FamilyNavigation).Include(p => p.GenderNavigation).Include(p => p.HasMobileNavigation).Include(p => p.ProfessionNavigation).Include(p => p.VehicleNavigation);               
                return View(await kalyanadiaryContex.ToListAsync());
          
        }
       public List<Person> GetPeople()
        {
            return _context.Person.ToList();
            
        }
        // GET: PeopleArea/People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .Include(p => p.EducationNavigation)
                .Include(p => p.FamilyNavigation)
                .Include(p => p.GenderNavigation)
                .Include(p => p.HasMobileNavigation)
                .Include(p => p.ProfessionNavigation)
                .Include(p => p.VehicleNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            var logs = await _context.UserLog.Where(a=>a.UserId==id).FirstOrDefaultAsync();
            ViewBag.log = logs;
            var posts =await _context.Post.Where(p => p.UserId == id).ToListAsync();
            ViewBag.pts = posts;
            if (person == null)
            {
                return NotFound();
            }
           
          
            return View(person);
        }

        // GET: PeopleArea/People/Create
        public IActionResult Create()
        {
            
            
            ViewData["Education"] = new SelectList(_context.Education, "Id", "Type");
            ViewData["Family"] = new SelectList(_context.Family, "Id", "Name");
            ViewData["Gender"] = new SelectList(_context.Gender, "Id", "GenderName");
            ViewData["HasMobile"] = new SelectList(_context.Mobile, "Id", "MobileType");
            ViewData["Profession"] = new SelectList(_context.Profession, "Id", "Name");
            ViewData["Vehicle"] = new SelectList(_context.Vehicle, "Id", "Name");
            return View();
        }

        // POST: PeopleArea/People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Mobile,Email,Password,SonOrDaughterOf,Address,Hobby,Mobile,DateOfBirth,HasMobile,Gender,Education,Profession,Vehicle,Family,About,Married,RecoverEmail,Private")] Person person,IFormFile image)
        {
            string res = "";
            if (image!=null)
            {
                string DirPath = _ENV.ContentRootPath+"\\wwwroot\\Images\\PersonImages\\";
                string FileEx = Path.GetExtension(image.FileName);
                string fn = Guid.NewGuid()+FileEx;
                string FinalFileName = DirPath+fn;
                person.Image = fn;
             
                
                FileStream stream = new FileStream(FinalFileName, FileMode.Create);
               await image.CopyToAsync(stream);
            }
            if (person.RecoveryEmail == null)
            {
                person.RecoveryEmail = "Not Provided";
            }
            if (ModelState.IsValid)
            {
                IList <Person> p= _context.Person.ToList();
                foreach(Person per in p)
                {
                    if(per.Mobile==person.Mobile)
                    {
                        ModelState.AddModelError(string.Empty, "This Mobile Number Already Exist");
                        return View(person);
                    }
                }

                {
                    //  log.UserIp = accessor.ActionContext.HttpContext.Connection.RemoteIpAddress.ToString();
                    person.City = "Kalyana";
                    
                    person.CreatedDate = DateTime.Now;
                    person.ModifiedDate = DateTime.Now;
                    Validations validation = new Validations();
                    res = validation.PersonValidation(person);
                    if (res == "")
                    {
                        _context.Add(person);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, res);
                        return View(person);
                    }

                }
                return RedirectToAction(nameof(Index));
            }
            
            ViewData["Education"] = new SelectList(_context.Education, "Id", "Upto", person.Education);
            ViewData["Family"] = new SelectList(_context.Family, "Id", "Name", person.Family);
            ViewData["Gender"] = new SelectList(_context.Gender, "Id", "GenderName", person.Gender);
            ViewData["HasMobile"] = new SelectList(_context.Mobile, "Id", "MobileType", person.HasMobile);
            ViewData["Profession"] = new SelectList(_context.Profession, "Id", "Name", person.Profession);
            ViewData["Vehicle"] = new SelectList(_context.Vehicle, "Id", "Name", person.Vehicle);
            return View(person);
        }

        // GET: PeopleArea/People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            ViewData["Education"] = new SelectList(_context.Education, "Id", "Type", person.Education);
            ViewData["Family"] = new SelectList(_context.Family, "Id", "Name", person.Family);
            ViewData["Gender"] = new SelectList(_context.Gender, "Id", "GenderName", person.Gender);
            ViewData["HasMobile"] = new SelectList(_context.Mobile, "Id", "HasMobile", person.HasMobile);
            ViewData["Profession"] = new SelectList(_context.Profession, "Id", "Name", person.Profession);
            ViewData["Vehicle"] = new SelectList(_context.Vehicle, "Id", "Name", person.Vehicle);
            ViewBag.d = person.DateOfBirth;
            return View(person);
        }

        // POST: PeopleArea/People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Password,SonOrDaughterOf,Address,Hobby,Mobile,DateOfBirth,HasMobile,Gender,RecoveryEmail,Education,Profession,Vehicle,Family,About,Married,CreatedDate,ModifiedDate,City,Image,Private")] Person person,IFormFile image)
        {
            if (id != person.Id)
            {
                return NotFound();
            }

KalyanaInfo/Areas/PeopleArea/Views/People/Create.cshtml
@model KalyanaInfo.Models.Person

@{
    Layout = "_Layout";
    ViewData["Title"] = "Create";
}

<h1>Signup For Kalyana</h1>


<div class="row align-content-center" style="background-color:lightblue">
    <div class="col-md-6">
        <form asp-action="Create" id="PersonForm" name="PersonForm" enctype="multipart/form-data">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <p><input id="image" name="image" type="file" accept="image/*" onchange="loadFile(event)" style="display: none;" required></p>
                <p><label for="image" style="cursor: pointer;">Upload Image</label></p>
                <p id="#img"><img id="output" width="60" height="60" style="border:1px solid black;border-radius:50%" /></p>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" placeholder="Enter Full Name" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" type="email" class="form-control" placeholder="Enter Correecte Email" required />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" required />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SonOrDaughterOf" class="control-label"></label>
                <input asp-for="SonOrDaughterOf" class="form-control" required />
                <span asp-validation-for="SonOrDaughterOf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" required />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hobby" class="control-label"></label>
                <input asp-for="Hobby" class="form-control" required />
                <span asp-validation-for="Hobby" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mobile" class="control-label"></label>
                <input asp-for="Mobile" class="form-control" pattern="[0-9]{11}" maxlength="11" min="11" placeholder="03036405108" required />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control"  />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HasMobile" class="control-label d-block"></label>
                <select asp-for="HasMobile" class="form-control" asp-items="ViewBag.HasMobile"></select>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label d-block"></label>
                <select asp-for="Gender" class="form-control" asp-items="ViewBag.Gender"></select>
            </div>
            <div class="form-group">
                <label asp-for="Education" class="control-label d-block"></label>
                <select asp-for="Education" class="form-control" asp-items="ViewBag.Education"></select>
            </div>
            <div class="form-group">
                <label asp-for="Profession" class="control-label d-block "></label>
                <select asp-for="Profession" class="form-control" asp-items="ViewBag.Profession"></select>
            </div>
            <div class="form-group">
                <label asp-for="Vehicle" class="control-label d-block"></label>
                <select asp-for="Vehicle" class="form-control" asp-items="ViewBag.Vehicle"></select>
            </div>
            <div class="form-group">
                <label asp-for="Family" class="control-label d-block"></label>
                <select asp-for="Family" class="form-control" asp-items="ViewBag.Family"></select>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label "></label>
                <textarea asp-for="About" class="form-control" required></textarea>
                <span asp-validation-for="About" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="RecoveryEmail" class="control-label ">Recovery Email(*Optional)</label>
                <input asp-for="RecoveryEmail" class="form-control" type="email" />
                <span asp-validation-for="RecoveryEmail" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary active" style="margin-right:10px">
                        <input type="radio" asp-for="Married" autocomplete="off" checked value="true"> Married:
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" asp-for="Married" autocomplete="off" value="false"> Not Married:
                    </label>

                </div>
            </div>
            <div class="form-group">
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary active" style="margin-right:10px">
                        <input type="radio" asp-for="Private" autocomplete="off" checked value="true"> Private
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" asp-for="Private" autocomplete="off" value="false"> Public
                    </label>

                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts
{
    <script>
      
        var loadFile = function (event) {
            $("#img").fadeIn();
            var image = document.getElementById('output');
            image.src = URL.createObjectURL(event.target.files[0]);
        };
       


        $('#Family').select2({
            selectOnClose: true
        });
        $('#Profession').select2({
            selectOnClose: true
        });
        $('#Vehicle').select2({
            selectOnClose: true
        });
        $('#Gender').select2({
            selectOnClose: true
        });
        $('#Gender').select2({
            selectOnClose: true
        });

        $('#HasMobile').select2({
            selectOnClose: true
        });
        $('#Education').select2({
            selectOnClose: true
        });
       
    </script>

}

KalyanaInfo/Areas/PeopleArea/Views/People/Delete.cshtml
@model KalyanaInfo.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SonOrDaughterOf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SonOrDaughterOf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hobby)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hobby)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mobile)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecoveryEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecoveryEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.About)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Married)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Married)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EducationNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EducationNavigation.Type)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FamilyNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FamilyNavigation.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenderNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenderNavigation.GenderName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasMobileNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasMobileNavigation.HasMobile)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfessionNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfessionNavigation.Name)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VehicleNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VehicleNavigation.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KalyanaInfo/Areas/PeopleArea/Views/People/ForgetPassword.cshtml
<link rel="stylesheet" href="~/css/Login.css">
<div class="login-page">
    <div class="form">
        <h3>Please Proide Email and Phone Number:</h3>
        <p>Note: Email you provided on Register Time</p>
        @Html.AntiForgeryToken()
        <form class="login-form" asp-action="ForgetPassword" method="post">
            <input type="text" placeholder="Mobile number" name="mob" id="mob" class="font-weight-bold" />
            <input type="email" placeholder="Email" name="email" id="email" class="font-weight-bold" />
            <input type="submit" value="SendMail" class="btn btn-info" id="sub" style="background-color:olivedrab" />
            
        </form>
    </div>
</div>
@ViewBag.er

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

KalyanaInfo/Areas/PeopleArea/Views/People/Index.cshtml
@model IEnumerable<KalyanaInfo.Models.Person>
            @*
control this search ajax not http
*@
 <h1>Peoples</h1>
   @if(Model!=null)
   { 

    @foreach (var item in Model.Reverse())
    {

    <div class="col-md-5 m-2 d-inline-block">

        <div class="card border-primary  d-inline-block col-md-6 " style="max-width: 30rem;">
            <a asp-action="Details" asp-route-id="@item.Id">
                <div class="card-header">
                    <span>
                        <img src="~/Images/PersonImages/@item.Image" alt="No Image" class="img-thumbnail" style="border-radius:100%;border:1px solid gray;display:inline-block" width="100" height="100" />
                    </span>
                    <span>@Html.DisplayFor(modelItem => item.Name)</span>
                    <p>     @Html.DisplayFor(modelItem => item.Email)</p>
                </div>
                <div class="card-body">
                    <p>Adress:@Html.DisplayFor(modelItem => item.Address)</p>
                </div>
                </a>
                <div>
                    
                    <a asp-action="Details" class="btn btn-info" asp-route-id="@item.Id">Details</a> 
    
                </div>
        </div>
    </div>

   

    }

   }

KalyanaInfo/Areas/PeopleArea/Views/People/LogIn.cshtml
<link rel="stylesheet" href="~/css/Login.css">
<div class="login-page">
    <div class="form">
        <h3>SignIn in Kalyana</h3>
        <p>@ViewBag.er</p>
          <form class="login-form" asp-action="LogIn" method="post">
              @ViewBag.nf
            <input type="text" placeholder="Mobile number" name="mob" id="mob" />
            <input type="password" placeholder="password" name="pass" id="pass" />
            <input type="submit" value="login" class="btn btn-info" id="sub" style="background-color:olivedrab"  />
            <p class="message">Not registered? <a asp-area="PeopleArea" asp-controller="People" asp-action="Create">Create an account</a></p>
            <p class="message">Forget Password? <a asp-area="PeopleArea" asp-controller="People" asp-action="ForgetPassword">Forget Password</a></p>

        </form>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

KalyanaInfo/Areas/PeopleArea/Views/People/Success.cshtml
@{
    Layout = "_Layout";
}

<h1 class="bg-success">SuccessFully sended Email with password</h1>
<h2>if not recieved then press this button for resend</h2>
<a asp-area="PeopleArea" asp-controller="People" asp-action="ForgetPassword" class="btn btn-danger">Resend</a>
<a asp-area="PeopleArea" asp-controller="People" asp-action="LogIn">Back To LoginPage</a>
<a asp-area="PeopleArea" asp-controller="People" asp-action="index">BackPeople</a>